# Generated by Django 4.2.22 on 2025-11-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_role_can_manage_schedules_role_can_view_schedules"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_use_registry",
            field=models.BooleanField(default=False),
        ),
    ]
